/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_LED_aliases.h"
#include "Pin_LED.h"
#include "Filter_1.h"
#include "Button_1.h"
#include "Pin_34_aliases.h"
#include "Pin_34.h"
#include "Pin_35_aliases.h"
#include "Pin_35.h"
#include "ADC_1.h"
#include "UART_1.h"
#include "Clock_UART.h"
#include "isrADC.h"
#include "Clock_1.h"
#include "Pin_152_aliases.h"
#include "Pin_152.h"
#include "Pin_153_aliases.h"
#include "Pin_153.h"
#include "Chart_1.h"
#include "Clock_2.h"
#include "Button_1_REG_0_aliases.h"
#include "Button_1_REG_0.h"
#include "Button_1_isrPoll.h"
#include "ADC_1_Ext_CP_Clk.h"
#include "ADC_1_Bypass_P32_aliases.h"
#include "ADC_1_Bypass_P32.h"
#include "ADC_1_IRQ.h"
#include "ADC_1_theACLK.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

